- name: Install redis repos
  package: 
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install Redis
  yum: 
    name: redis
    state: installed
    enablerepo: remi

- name: Start Redis
  service: 
    name: redis
    state: started
    enabled: yes
