- name: Install ESL-ERLANG
  package:
      name: yum install https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_22.2.1-1~centos~7_amd64.rpm
      state: present

- name: setup repos
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install RabbitMQ
  package:
    name: rabbitmq-server

- name: Start RabbitMQ
  service:
    name: mongod
    daemon_reload: yes
    state: restarted
    enabled: yes