- name: clone the repo
  import_tasks: clone.yml
  when: action == "clone"

- name: cleanup the repo
  import_tasks: cleanup.yml
  when: action == "clean"

- name: Setup Application Directory
  file:
    path: /root/ROBO-SHOP 
    state: directory
