- name: Copy Mongo Repo
  hosts: all
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  package: 
    name: mongodb-org
    state:  present

- name: replace a IP in MongoDB
  replace:
    path: /tmp/mongod.conf
    regexp: "127.0.0.0"
    replace: "0.0.0.0" 

- name: Start MongoDB
  service:
    name: mongod
    daemon_reload: yes
    state: restarted
    enabled: yes
    
    


