- name: copy {{APP_NAME}} Appliction
  copy:
    src: /tmp/robo-shop/{{APP_NAME}}
    dest: "{{APP_ROOT_DIR}}"
    remote_src: yes

- name: install NodeJS Dependencies
  shell: npm install
  args:
    chdir: "{{APP_DIR}}"

- name: Configure Systemd Service for {{APP_NAME}} Application
  replace:
    path: "{{APP_DIR}}/systemd.service"
    regexp: "ROOT-DIR"
    replace: "{{APP_ROOT_DIR}}"
  
- name: copy systemd service file
  copy:
    src: "{{APP_DIR}}/systemd.service"
    dest: "/etc/systemd/system/{{APP_NAME}}.service"
    remote_src: yes


- name: systemd Daemon-reload
  systemd:
    daemon_reload: yes

- name: start {{APP_NAME}} Application
  systemd:
    name: "{{APP_NAME}}"
    state: restarted
    enabled: yes
