- name: Get the Download URL of NodeJS
  shell: curl -s https://nodejs.org/en/download/ | xargs -n1 | grep linux-x64.tar | sed -e 's|=| |g' -e 's|>| |g'| xargs -n1 | grep ^http
  register: out

- name: Download NodeJS
  unarchive:
    src: "{{out.stdout}}"
    dest: /opt
    remote_src: yes
    extra_opts:
    - --strip=1

#- name: Rename NodeJS Directory
#  shell: mv /opt/node-v12.16.3-linux-x64 /opt/node

- name: NodeJS links
