- name: sample
  hosts: all
  tasks:
    - name: Run uptime
      shell: uptime

    - name: Install vim
      package:
         state: present
         name: vim
         use: auto

    - name: Install zip     
      package:
          state: present
          name: zip
          use: auto