- name: variables demo
  hosts: all
  ## Declare variables on play level
  vars: 
   URL: play.google.com

  tasks:
    - name: print URL
      debug:
        msg: "URL = {{URL}}"

    - name: Print URL one more time
      debug:
        msg: "URL = {{URL}}"    

