- name: variables demo
  hosts: all
  ## Declare variables on play level
  vars: 
   URL: play.google.com

  tasks:
    - name: print URL
      debug:
        msg: "URL = {{URL}}"

    - name: Print URL one more time
      debug:
        msg: "URL = {{URL}}"    

## Observation: we can declare a variable  in a play and that variable can be available to all the tasks in the play

- name: variable demo from tasks
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: print URL
      debug: 
        msg:  "URL = {{URL}}"
      vars:
        URL: task.google.com
        # we can declares variable from task level as well

# Observation: We can have a declare variable in task level but the local variable task going to have higher precedence 

- name: variable for a demo
  hosts: all
  vars:
    URL: play.google.com
  vars_files:
    - vars.yml
  
  tasks:
    - name: print URL 
      debug:
        msg: "URL = {{URL}}"

# Obseravation: vars_files is having high perecdence than vars. 

- name: variable from user input
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no       
  vars_files:
    - vars.yml

  tasks:
    - name: print 
        msg: "URL = {{URL}}"
      tasks:
        URL: task.google.com
# Observation: vars_files going to have higher precedence vars_prompt and vars.


- name: Variable fro CLI
  hosts: all
  tasks:
    - name: print URL
      debug:
        msg: "URL = {{URL}}"

# Observation: the highest precedence goes to -e cli



#-command line
#-vars_file
#-vars_prompt
#-task
#-vars