- name: Demo on register variable
  hosts: all
  tasks:
    - name: uptime command
      shell: uptime
      register: out
    
    - name: print registered variable
        debug:
        msg: "{{out}}"