- name: Demo of Conditionals
  hosts: all
  tasks:
  - shell: /bin/true
    register: result
    ignore_errors: True 

  - debug:
    msg: Nice, Good Job
    when: result is succeeded.

  - debug:
    msg: Bad, Try Again
    when: result is Failed.