- name: Demo of Conditionals
  hosts: all
  tasks:
    - command: /bin/true
      register: result

    - debug:
      msg: Nice, Good Job
      when: result is success

    - debug: 
      msg: Bad, Try Again
      when: result is fail
