- name: Demo of Conditionals
  hosts: all
  tasks:
    - command: /bin/false
      register: result
    
    - name: print OK
      debug:
        msg: Nice, Good Job
      when: result is succeeded.

    - name: Print NotOk
      debug:
        msg: Bad, Try Again
      when: result is Failed.