- name: Demo of Conditionals
  hosts: all
  tasks:
    - command: /bin/true
      register: result
    - debug:
      msg: Nice, God Job
      when: result is failed
    - debug:
      msg: Bad, Try Again
      when: