- name: Demo of Conditionals
  hosts: all
  tasks:
    - command: /bin/false
      register: result
      ignore_errors: True
    
    - name: print OK
      debug:
        msg: Nice, Good Job
      when: result is succeeded
    
    - name: print NotOK
      debug:
        msg: Bad, Try Again
      when: result is failed
