- name: Demo of Conditionals
  hosts: all
  tasks:
    - command: /bin/true
      register: result
    
    - name: print OK
      tasks:
        debug:
          msg: Nice, Good Job
        when: result is succeeded.

    - name: Print NotOk
      tasks:
        debug:
          msg: Bad, Try Again
        when: result is Failed.